services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - backend

  ftps:
    image: stilliard/pure-ftpd
    container_name: ftps_container
    restart: always
    environment:
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: ftppassword
      FTP_USER_HOME: /home/ftpusers
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./ftp-data:/home/ftpusers
    networks:
      - backend

  app:
    build: .
    container_name: nodejs_app
    restart: always
    depends_on:
      - mysql
      - ftps
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - backend

networks:
  backend:
    driver: bridge